# Generated by Django 6.0.3 on 2026-06-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Danh mục thực đơn',
                'verbose_name_plural': 'Danh mục thực đơn',
                'db_table': 'menu_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Đặt bàn được xác nhận'), ('booking_reminder', 'Nhắc nhở đặt bàn'), ('booking_cancelled', 'Đặt bàn bị hủy'), ('status_update', 'Cập nhật trạng thái đặt bàn'), ('staff_action', 'Nhân viên thao tác'), ('system', 'Thông báo hệ thống')], max_length=50),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.category')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Món ăn',
                'db_table': 'menu_items',
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
