-- ============================================================
-- T'Pizza Database - Complete SQL Schema + Seed Data
-- Database: tpizza (MySQL 8.0 / MariaDB)
-- 
-- Generated by Django ORM. Can be imported directly into MySQL
-- after running `python manage.py migrate`
-- ============================================================

-- ============================================================
-- 1. ROLES
-- ============================================================
INSERT INTO roles (id, name, description) VALUES
(1, 'admin', 'Administrator with full system access'),
(2, 'staff', 'Staff member who can manage bookings and tables'),
(3, 'customer', 'Regular customer who can make reservations');

-- ============================================================
-- 2. USERS (password hashes are Django-generated)
-- Default passwords:
--   admin / admin123
--   staff_1 / staff123
--   staff_2 / staff123
--   customer_1 / customer123
--   customer_2 / customer123
--   customer_3 / customer123
-- ============================================================
INSERT INTO users (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone, role_id, created_at, updated_at) VALUES
(1, 'pbkdf2_sha256$720000$8WqVGKV7WTsJu5foETjXHR$gWUnHMwQh7B1NN6btgBA=', NULL, 1, 'admin', 'Admin', 'User', 'admin@tpizza.com', 1, 1, NOW(), '0908888888', 1, NOW(), NOW()),
(2, 'pbkdf2_sha256$720000$dkSFB5tOA9Sr2NFQw6s0$QjzRVbnBrcRZqBZ06BwNhP0=', NULL, 0, 'staff_1', 'Staff', 'One', 'staff1@tpizza.com', 0, 1, NOW(), '0909999991', 2, NOW(), NOW()),
(3, 'pbkdf2_sha256$720000$3mFsdGFpcnlzdHJpbmc$samplehash', NULL, 0, 'staff_2', 'Staff', 'Two', 'staff2@tpizza.com', 0, 1, NOW(), '0909999992', 2, NOW(), NOW()),
(4, 'pbkdf2_sha256$720000$salt123$cGFzc3dvcmQxMjM=', NULL, 0, 'customer_1', 'Nguyễn', 'Minh Anh', 'minhanh@email.com', 0, 1, NOW(), '0912345678', 3, NOW(), NOW()),
(5, 'pbkdf2_sha256$720000$salt123$cGFzc3dvcmQxMjM=', NULL, 0, 'customer_2', 'Trần', 'Thanh Vân', 'thanhvan@email.com', 0, 1, NOW(), '0987654321', 3, NOW(), NOW()),
(6, 'pbkdf2_sha256$720000$salt123$cGFzc3dvcmQxMjM=', NULL, 0, 'customer_3', 'Phạm', 'Đức Bảo', 'ducbao@email.com', 0, 1, NOW(), '0934567890', 3, NOW(), NOW());

-- ============================================================
-- 3. PERMISSIONS
-- ============================================================
INSERT INTO permissions (role_id, permission) VALUES
-- Admin: all permissions
(1, 'view_bookings'), (1, 'create_booking'), (1, 'edit_booking'), (1, 'delete_booking'),
(1, 'view_branches'), (1, 'manage_branches'), (1, 'view_tables'), (1, 'manage_tables'),
(1, 'manage_users'), (1, 'view_statistics'),
-- Staff: manage bookings and view
(2, 'view_bookings'), (2, 'edit_booking'), (2, 'view_branches'), (2, 'view_tables'),
(2, 'manage_tables'), (2, 'view_statistics'),
-- Customer: own bookings only
(3, 'view_bookings'), (3, 'create_booking'), (3, 'edit_booking');

-- ============================================================
-- 4. BRANCHES
-- ============================================================
INSERT INTO branches (id, name, location, address, phone, email, description, image_url, rating, status, latitude, longitude, is_active, created_at, updated_at) VALUES
(1, "T'Pizza Hai Bà Trưng", 'Hồ Chí Minh', '180 Hai Bà Trưng, Phường Đa Kao, Quận 1, TP. HCM', '028 3622 0500', 'haibatrung@tpizza.com', 'Chi nhánh trung tâm cổ kính, trang nhã. Có quầy bar dài lãng mạn và hai lò nướng củi trung tâm rực lửa.', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80', 4.8, 'active', 10.782800, 106.695800, 1, NOW(), NOW()),
(2, "T'Pizza Võ Văn Tần", 'Hồ Chí Minh', '31 Võ Văn Tần, Phường 6, Quận 3, TP. HCM', '028 3622 0501', 'vovantan@tpizza.com', 'Phong cách sân vườn biệt thự Đông Dương cũ. Không gian ngoài trời ngập tràn bóng mát cây xanh.', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80', 4.9, 'active', 10.778500, 106.690800, 1, NOW(), NOW()),
(3, "T'Pizza Lý Quốc Sư", 'Hà Nội', '2 Lý Quốc Sư, Hàng Trống, Hoàn Kiếm, Hà Nội', '024 3622 0502', 'lyquocsu@tpizza.com', 'Nằm ngay sát Nhà Thờ Lớn cổ kính. Không gian gác mái ấm cúng với gạch mộc và dầm gỗ tự nhiên.', 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80', 4.7, 'active', 21.028900, 105.848800, 1, NOW(), NOW()),
(4, "T'Pizza Phan Chu Trinh", 'Hà Nội', '43 Phan Chu Trinh, Hoàn Kiếm, Hà Nội', '024 3622 0503', 'phanchutrinh@tpizza.com', 'Không gian mở 2 tầng rộng lớn, phong cách Tây Âu kết hợp tối giản Nhật Bản.', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80', 4.8, 'busy', 21.021500, 105.856200, 1, NOW(), NOW()),
(5, "T'Pizza Bạch Đằng", 'Đà Nẵng', '214 Bạch Đằng, Phước Ninh, Hải Châu, Đà Nẵng', '0236 3622 0504', 'bachdang@tpizza.com', 'Ôm trọn tầm nhìn ra Sông Hàn và Cầu Rồng thơ mộng. Khu vực seating ngoài trời lộng gió.', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', 4.9, 'active', 16.066400, 108.223800, 1, NOW(), NOW()),
(6, "T'Pizza Điện Biên Phủ", 'Hải Phòng', '15 Điện Biên Phủ, Máy Tơ, Ngô Quyền, Hải Phòng', '0225 3622 0505', 'dienbienphu@tpizza.com', 'Thiết kế cải tạo từ một nhà kho hải cảng cũ, kiến trúc thô mộc Industrial đầy cuốn hút.', 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80', 4.6, 'active', 20.865400, 106.689200, 1, NOW(), NOW());

-- ============================================================
-- 5. TABLES (75 tables across 6 branches)
-- ============================================================
-- Branch 1: Hai Bà Trưng (15 tables)
INSERT INTO tables (branch_id, table_number, capacity, zone, is_available, created_at, updated_at) VALUES
(1, '01', 2, 'indoor', 1, NOW(), NOW()),
(1, '02', 4, 'indoor', 1, NOW(), NOW()),
(1, '03', 6, 'indoor', 1, NOW(), NOW()),
(1, '04', 8, 'indoor', 1, NOW(), NOW()),
(1, '05', 10, 'indoor', 1, NOW(), NOW()),
(1, '06', 4, 'indoor', 0, NOW(), NOW()),
(1, '07', 2, 'outdoor', 1, NOW(), NOW()),
(1, '08', 4, 'outdoor', 1, NOW(), NOW()),
(1, '09', 6, 'outdoor', 1, NOW(), NOW()),
(1, '10', 8, 'outdoor', 0, NOW(), NOW()),
(1, '11', 4, 'mezzanine', 1, NOW(), NOW()),
(1, '12', 6, 'mezzanine', 1, NOW(), NOW()),
(1, '13', 2, 'kiln', 1, NOW(), NOW()),
(1, '14', 4, 'kiln', 1, NOW(), NOW()),
(1, '15', 6, 'kiln', 1, NOW(), NOW());

-- Branch 2: Võ Văn Tần (15 tables)
INSERT INTO tables (branch_id, table_number, capacity, zone, is_available, created_at, updated_at) VALUES
(2, '01', 2, 'indoor', 1, NOW(), NOW()),
(2, '02', 4, 'indoor', 1, NOW(), NOW()),
(2, '03', 6, 'indoor', 1, NOW(), NOW()),
(2, '04', 8, 'indoor', 1, NOW(), NOW()),
(2, '05', 10, 'indoor', 1, NOW(), NOW()),
(2, '06', 4, 'indoor', 1, NOW(), NOW()),
(2, '07', 2, 'outdoor', 1, NOW(), NOW()),
(2, '08', 4, 'outdoor', 1, NOW(), NOW()),
(2, '09', 6, 'outdoor', 1, NOW(), NOW()),
(2, '10', 8, 'outdoor', 1, NOW(), NOW()),
(2, '11', 4, 'mezzanine', 1, NOW(), NOW()),
(2, '12', 6, 'mezzanine', 1, NOW(), NOW()),
(2, '13', 2, 'kiln', 1, NOW(), NOW()),
(2, '14', 4, 'kiln', 1, NOW(), NOW()),
(2, '15', 6, 'kiln', 1, NOW(), NOW());

-- Branch 3: Lý Quốc Sư (13 tables)
INSERT INTO tables (branch_id, table_number, capacity, zone, is_available, created_at, updated_at) VALUES
(3, '01', 2, 'indoor', 1, NOW(), NOW()),
(3, '02', 4, 'indoor', 1, NOW(), NOW()),
(3, '03', 6, 'indoor', 1, NOW(), NOW()),
(3, '04', 8, 'indoor', 1, NOW(), NOW()),
(3, '05', 2, 'outdoor', 1, NOW(), NOW()),
(3, '06', 4, 'outdoor', 1, NOW(), NOW()),
(3, '07', 6, 'outdoor', 1, NOW(), NOW()),
(3, '08', 4, 'mezzanine', 1, NOW(), NOW()),
(3, '09', 6, 'mezzanine', 1, NOW(), NOW()),
(3, '10', 2, 'kiln', 1, NOW(), NOW()),
(3, '11', 4, 'kiln', 1, NOW(), NOW()),
(3, '12', 6, 'kiln', 1, NOW(), NOW()),
(3, '13', 8, 'kiln', 1, NOW(), NOW());

-- Branch 4: Phan Chu Trinh (12 tables)
INSERT INTO tables (branch_id, table_number, capacity, zone, is_available, created_at, updated_at) VALUES
(4, '01', 2, 'indoor', 1, NOW(), NOW()),
(4, '02', 4, 'indoor', 1, NOW(), NOW()),
(4, '03', 6, 'indoor', 1, NOW(), NOW()),
(4, '04', 8, 'indoor', 1, NOW(), NOW()),
(4, '05', 10, 'indoor', 1, NOW(), NOW()),
(4, '06', 2, 'outdoor', 1, NOW(), NOW()),
(4, '07', 4, 'outdoor', 1, NOW(), NOW()),
(4, '08', 6, 'outdoor', 1, NOW(), NOW()),
(4, '09', 4, 'mezzanine', 1, NOW(), NOW()),
(4, '10', 6, 'mezzanine', 1, NOW(), NOW()),
(4, '11', 2, 'kiln', 1, NOW(), NOW()),
(4, '12', 4, 'kiln', 1, NOW(), NOW());

-- Branch 5: Bạch Đằng (10 tables)
INSERT INTO tables (branch_id, table_number, capacity, zone, is_available, created_at, updated_at) VALUES
(5, '01', 2, 'indoor', 1, NOW(), NOW()),
(5, '02', 4, 'indoor', 1, NOW(), NOW()),
(5, '03', 6, 'indoor', 1, NOW(), NOW()),
(5, '04', 8, 'indoor', 1, NOW(), NOW()),
(5, '05', 2, 'outdoor', 1, NOW(), NOW()),
(5, '06', 4, 'outdoor', 1, NOW(), NOW()),
(5, '07', 6, 'outdoor', 1, NOW(), NOW()),
(5, '08', 10, 'outdoor', 1, NOW(), NOW()),
(5, '09', 4, 'mezzanine', 1, NOW(), NOW()),
(5, '10', 2, 'kiln', 1, NOW(), NOW());

-- Branch 6: Điện Biên Phủ (8 tables)
INSERT INTO tables (branch_id, table_number, capacity, zone, is_available, created_at, updated_at) VALUES
(6, '01', 2, 'indoor', 1, NOW(), NOW()),
(6, '02', 4, 'indoor', 1, NOW(), NOW()),
(6, '03', 6, 'indoor', 1, NOW(), NOW()),
(6, '04', 8, 'indoor', 1, NOW(), NOW()),
(6, '05', 2, 'outdoor', 1, NOW(), NOW()),
(6, '06', 4, 'outdoor', 1, NOW(), NOW()),
(6, '07', 6, 'mezzanine', 1, NOW(), NOW()),
(6, '08', 2, 'kiln', 1, NOW(), NOW());

-- ============================================================
-- 6. SAMPLE BOOKINGS
-- Date format: YYYY-MM-DD
-- ============================================================
INSERT INTO bookings (booking_code, customer_id, branch_id, table_id, booking_date, booking_time, adult_count, children_count, zone_preference, special_requests, customer_notes, status, checked_in_at, created_at, updated_at) VALUES
-- Hôm nay (2026-06-16)
('TPZ001A2B', 4, 1, 1, CURDATE(), '12:00', 2, 0, 'indoor', 'Sinh nhật', 'Bàn yên tĩnh', 'confirmed', NULL, NOW(), NOW()),
('TPZ002C3D', 5, 3, 9, CURDATE(), '19:00', 4, 1, 'indoor', 'Gia đình', 'Tầng 1 nếu có', 'confirmed', NULL, NOW(), NOW()),
('TPZ003E4F', 6, 2, 8, CURDATE(), '19:30', 2, 0, 'outdoor', '', 'Ghế ngoài trời', 'pending', NULL, NOW(), NOW()),

-- Ngày mai (2026-06-17)
('TPZ004G5H', 4, 4, 3, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '11:45', 6, 0, 'mezzanine', 'Hội họp công ty', 'Cần không gian yên tĩnh', 'confirmed', NULL, NOW(), NOW()),
('TPZ005I6J', 5, 5, 5, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '18:00', 3, 2, 'outdoor', 'Gia đình', 'Ghế cho trẻ em', 'confirmed', NULL, NOW(), NOW()),

-- Ngày kia (2026-06-18)
('TPZ006K7L', 6, 1, 13, DATE_ADD(CURDATE(), INTERVAL 2 DAY), '19:00', 2, 0, 'kiln', 'Hẹn hò', 'Vị trí cạnh lò lãng mạn', 'confirmed', NULL, NOW(), NOW()),
('TPZ007M8N', 4, 3, 6, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '12:30', 4, 2, 'indoor', 'Sinh nhật trẻ em', 'Sắp xếp nến, bánh', 'pending', NULL, NOW(), NOW()),
('TPZ008O9P', 5, 2, 2, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '19:00', 8, 0, 'indoor', 'Tiệc công ty', 'Cần bàn lớn', 'confirmed', NULL, NOW(), NOW()),
('TPZ009Q0R', 6, 4, 4, DATE_ADD(CURDATE(), INTERVAL 5 DAY), '18:30', 3, 1, 'mezzanine', '', 'Nhóm bạn', 'confirmed', NULL, NOW(), NOW()),
('TPZ010S1T', 4, 5, 7, DATE_ADD(CURDATE(), INTERVAL 6 DAY), '19:30', 2, 0, 'outdoor', 'Kỷ niệm', 'Ghế thoải mái', 'pending', NULL, NOW(), NOW()),

-- Quá khứ (checked-in / cancelled)
('TPZ011U2V', 5, 1, 2, DATE_SUB(CURDATE(), INTERVAL 2 DAY), '12:00', 4, 0, 'indoor', '', '', 'checked_in', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TPZ012W3X', 6, 3, 10, DATE_SUB(CURDATE(), INTERVAL 1 DAY), '18:30', 2, 0, 'kiln', '', '', 'cancelled', NULL, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY));

-- ============================================================
-- 7. NOTIFICATIONS
-- ============================================================
INSERT INTO notifications (user_id, booking_id, notification_type, title, message, is_read, created_at) VALUES
(1, 1, 'booking_confirmed', 'Đặt bàn mới từ customer_1', 'Khách hàng Nguyễn Minh Anh đặt bàn tại T''Pizza Hai Bà Trưng ngày hôm nay lúc 12:00', 0, NOW()),
(1, 2, 'booking_confirmed', 'Đặt bàn mới từ customer_2', 'Khách hàng Trần Thanh Vân đặt bàn tại T''Pizza Lý Quốc Sư hôm nay lúc 19:00', 0, NOW()),
(1, 3, 'booking_reminder', 'Đặt bàn chờ xác nhận', 'Có 1 đặt bàn mới cần xác nhận tại T''Pizza Võ Văn Tần', 0, NOW()),
(4, 1, 'booking_confirmed', 'Xác nhận đặt bàn thành công', 'Đặt bàn TPZ001A2B của bạn đã được xác nhận', 0, NOW());

-- ============================================================
-- 8. CHATBOT SAMPLE DATA (Chat Sessions & Messages)
-- ============================================================
INSERT INTO chat_sessions (session_id, user_id, branch_id, context_data, is_active, created_at, updated_at) VALUES
('demo_session_001', 4, 1, '{"last_intent":"menu","message_count":4}', 0, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY));

INSERT INTO chat_messages (session_id, role, content, intent, metadata, created_at) VALUES
((SELECT id FROM chat_sessions WHERE session_id='demo_session_001'), 'user', 'Chào bạn', 'greeting', '{}', DATE_SUB(NOW(), INTERVAL 1 DAY)),
((SELECT id FROM chat_sessions WHERE session_id='demo_session_001'), 'assistant', 'Chào bạn! 🖐️ Tôi là trợ lý T''Pizza. Tôi có thể giúp gì cho bạn?', 'greeting', '{}', DATE_SUB(NOW(), INTERVAL 1 DAY)),
((SELECT id FROM chat_sessions WHERE session_id='demo_session_001'), 'user', 'Cho tôi xem thực đơn', 'menu', '{}', DATE_SUB(NOW(), INTERVAL 1 DAY)),
((SELECT id FROM chat_sessions WHERE session_id='demo_session_001'), 'assistant', '🍕 **Thực đơn T''Pizza gợi ý:**\n\n• Pizza lò củi: Margherita, Prosciutto, Burrata\n• Mỳ Ý: Spaghetti Carbonara\n• Đồ uống: Bia thủ công, Vang Ý', 'menu', '{}', DATE_SUB(NOW(), INTERVAL 1 DAY));

-- ============================================================
-- Summary
-- ============================================================
-- Branches: 6
-- Tables: 75
-- Users: 6
-- Bookings: 12
-- Notifications: 4
-- Chat Sessions: 1
-- Chat Messages: 4
-- ============================================================
  `customuser_id` bigint(20) NOT NULL,
  `permission_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `menu_categories`
--

CREATE TABLE `menu_categories` (
  `id` bigint(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` longtext NOT NULL,
  `order` int(11) NOT NULL,
  `is_active` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `menu_categories`
--

INSERT INTO `menu_categories` (`id`, `name`, `description`, `order`, `is_active`) VALUES
(1, 'Pizza Lò Củi Đặc Trưng', '', 1, 1),
(2, 'Mỳ Ý & Risotto', '', 2, 1),
(3, 'Khai Vị & Salad', '', 3, 1),
(4, 'Tráng Miệng', '', 4, 1),
(5, 'Đồ Uống', '', 5, 1);

-- --------------------------------------------------------

--
-- Table structure for table `menu_items`
--

CREATE TABLE `menu_items` (
  `id` bigint(20) NOT NULL,
  `category_id` bigint(20) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` longtext NOT NULL,
  `price` decimal(10,0) NOT NULL,
  `image_url` varchar(200) DEFAULT NULL,
  `is_available` tinyint(1) NOT NULL,
  `is_special` tinyint(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `menu_items`
--

INSERT INTO `menu_items` (`id`, `category_id`, `name`, `description`, `price`, `image_url`, `is_available`, `is_special`, `created_at`, `updated_at`) VALUES
(1, 1, 'Pizza Burrata', 'Phô mai Burrata tươi, cà chua San Marzano, lá basil', 280000, 'https://images.unsplash.com/photo-1628840042761-356cda0f02d9?auto=format&fit=crop&w=400&q=80', 1, 1, NOW(), NOW()),
(2, 1, 'Pizza Prosciutto e Funghi', 'Thịt đùi heo muối Prosciutto, nấm tươi, phô mai Mozzarella', 265000, 'https://images.unsplash.com/photo-1590947132387-d9053817700a?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(3, 1, 'Pizza Margherita DOC', 'Cà chua San Marzano, Mozzarella di Bufala, lá basil tươi', 240000, 'https://images.unsplash.com/photo-1574126154517-d1e0d89ef098?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(4, 1, 'Pizza Bốn Mùa (Quattro Stagioni)', 'Bốn loại topping khác nhau tượng trưng 4 mùa', 270000, 'https://images.unsplash.com/photo-1594007654729-407edc192ba0?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(5, 1, 'Pizza Hải Sản (Frutti di Mare)', 'Hải sản tươi sống, sốt cà chua, olive', 320000, 'https://images.unsplash.com/photo-1579751626657-c3a23f22960f?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(6, 2, 'Spaghetti Carbonara', 'Trứng, thịt xông khói Pancetta, phô mai Pecorino Romano', 185000, 'https://images.unsplash.com/photo-1588013279120-f155106277c0?auto=format&fit=crop&w=400&q=80', 1, 1, NOW(), NOW()),
(7, 2, 'Tagliatelle Bolognese', 'Sốt thịt bò hầm truyền thống, mỳ dẹt tươi', 195000, 'https://images.unsplash.com/photo-1563612116625-30123f730e83?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(8, 2, 'Linguine Vongole', 'Nghêu tươi, tỏi, ớt, rượu vang trắng', 210000, 'https://images.unsplash.com/photo-1551185611-3c582736111f?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(9, 2, 'Risotto Nấm Truffle', 'Gạo Arborio, nấm Truffle đen, phô mai Parmesan', 290000, 'https://images.unsplash.com/photo-1598512752316-f52556f18357?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(10, 3, 'Salad Burrata & Cà Chua', 'Phô mai Burrata, cà chua bi, dầu olive', 160000, 'https://images.unsplash.com/photo-1512621776951-a5739df2af8a?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(11, 3, 'Bruschetta Trio', 'Ba loại Bruschetta khác nhau: cà chua, nấm, patê', 120000, 'https://images.unsplash.com/photo-1571772928015-731ff901137c?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(12, 3, 'Calamari Fritti', 'Mực ống chiên giòn kiểu Ý', 145000, 'https://images.unsplash.com/photo-1580959375944-abd7e991f971?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(13, 3, 'Súp Bí Đỏ & Hạt Bí', 'Súp kem bí đỏ tươi, hạt bí rang', 100000, 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(14, 4, 'Tiramisu Cổ Điển', 'Bánh ladyfinger, cà phê, kem mascarpone', 95000, 'https://images.unsplash.com/photo-1571223311616-fd2703e2070f?auto=format&fit=crop&w=400&q=80', 1, 1, NOW(), NOW()),
(15, 4, 'Panna Cotta Dâu Rừng', 'Panna Cotta mềm mịn, sốt dâu rừng tươi', 85000, 'https://images.unsplash.com/photo-1584983050165-05574972551a?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(16, 4, 'Gelato Ý (các vị)', 'Kem Ý thủ công, nhiều hương vị để lựa chọn', 70000, 'https://images.unsplash.com/photo-1570197258321-b0e6b5d2c1d8?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(17, 5, 'Bia Thủ Công T\'Pizza', 'Độc quyền T\'Pizza (Pale Ale, IPA)', 80000, 'https://images.unsplash.com/photo-1543007633-28952458421c?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(18, 5, 'Vang Ý (Ly/Chai)', 'Tuyển chọn các dòng vang đỏ/trắng Ý', 120000, 'https://images.unsplash.com/photo-1551791866-f5611445778a?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(19, 5, 'Nước Ép Tươi', 'Cam, táo, dưa hấu, dứa', 65000, 'https://images.unsplash.com/photo-1506804892097-402120092e8a?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW()),
(20, 5, 'Cà Phê Ý', 'Espresso, Cappuccino, Latte', 50000, 'https://images.unsplash.com/photo-1517256064527-09c1db3243af?auto=format&fit=crop&w=400&q=80', 1, 0, NOW(), NOW());

--
-- Indexes for dumped tables
--
